name: patch 
description: ''

inputs:
  token:
    description: "GitHub Token used to authenticate against a repository for Git context."
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        token: "${{ inputs.token }}"

    - name: Bump version
      shell: bash
      run: |
        GITHUB_REF=${GITHUB_REF//*\/}
        CURRENT_VERSION="$(git ls-remote -q --tags | awk -F/ '{ print $3}'| sort -Vr | grep "^${GITHUB_REF//.x}" | head -n1 )";
        NEXT_VERSION=$(docker run alpine/semver semver -c -i patch ${CURRENT_VERSION});

        git tag ${NEXT_VERSION};
        git push --tags origin;

