name: 'Building LXC' 

# Allow repository modyfication;
permissions:
  contents: write

on:
# Trigger this workflow on each tag push

  push:
# Specify that it should only trigger when a tag is pushed.
# The wildcard '*' means any tag name will match.
    tags:
      - '*'

# Allow manually triggering this workflow from the Actions tab in GitHub.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
      
    defaults:
      run:
        shell: bash
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
           
      - name: 'Prepare'
        run: |
          make prepare 

      - name: 'Execute'
        run: |
          make execute 

      - name: 'Release'
        run: |
            
            cd ansible;
            TAG="$(git ls-remote -q --tags --sort="v:refname" | tail -n1 | sed 's/.*\///; s/\^{}//')"

            NEW_NAME="${{ github.event.repository.name }}-${TAG}";
            NEW_NAME="${NEW_NAME//[^[:alnum:]]/_}.tar.xz"

            mv rootfs.tar.xz ${NEW_NAME};
            gh release create ${TAG} ${NEW_NAME};

        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}

